#!/bin/bash

# Fail fast so partial workspace-sync runs do not silently continue.
set -e

echo "--- Starting Workspace Sync ---"

# 1) Refresh inventory artifacts generated by workspace automation.
echo "Running auto_register.py..."
python3 workspace-automation/src/auto_register.py
echo "file_registry.json and SYSTEM_INVENTORY.md updated."

# Stage generated inventory artifacts explicitly before broader staging.
git add workspace-automation/file_registry.json SYSTEM_INVENTORY.md
echo "file_registry.json and SYSTEM_INVENTORY.md staged."

# 2) Generate commit message text.
# NOTE: This is currently a placeholder, not dynamic generation.
# Replace this block with your LLM/templated commit-message pipeline when ready.
echo "Generating AI-driven commit message (placeholder)..."
# Example integration point:
# COMMIT_MESSAGE=$(python3 -c "from your_llm_utils import generate_commit_message; print(generate_commit_message())")
COMMIT_MESSAGE="feat: Implemented comprehensive hybrid LLM system including core engine, specialized MCP services, resilience, and benchmarking. Updated documentation."
echo "Generated commit message: \"$COMMIT_MESSAGE\""

# 3) Commit current workspace state.
echo "Staging all changes and committing..."
git add .
if git diff --cached --quiet; then
    echo "No staged changes to commit. Skipping commit and changelog update."
else
    git commit -m "$COMMIT_MESSAGE"
    echo "Git commit successful."

    # 4) Append a simple changelog entry.
    # This is intentionally minimal and can be replaced with PR- or release-based generation.
    echo "Updating CHANGELOG.md..."
    echo -e "\n## $(date +%Y-%m-%d)\n" >> CHANGELOG.md
    echo -e "$COMMIT_MESSAGE\n" >> CHANGELOG.md
    echo "CHANGELOG.md updated."
fi

# 5) Trigger a full project snapshot through the system_utility MCP server.
echo "Creating project snapshot via SystemUtilityServer..."
python3 workspace-automation/src/run_orchestrator_tool.py \
    create_project_snapshot "{}" system_utility
echo "Project snapshot creation initiated."
