#!/bin/bash

# Fail fast so partial workspace-sync runs do not silently continue.
set -e

echo "--- Starting Workspace Sync ---"

# 0) Run pre-sync backup.
bash "$(dirname "$0")/orchestrated_backup.sh"

# 1) Refresh inventory artifacts generated by workspace automation.
echo "Running auto_register.py..."
python3 workspace-automation/src/auto_register.py
echo "file_registry.json and SYSTEM_INVENTORY.md updated."

# Stage generated inventory artifacts explicitly before broader staging.
git add workspace-automation/file_registry.json SYSTEM_INVENTORY.md
echo "file_registry.json and SYSTEM_INVENTORY.md staged."

# 2) Generate commit message text.
# Dynamically generate commit message from recent git history.
COMMIT_MESSAGE=$(git log --oneline -5 | head -1 | sed 's/^[a-f0-9]* //')
echo "Generated commit message: \"$COMMIT_MESSAGE\""

# 3) Commit current workspace state.
echo "Staging all changes and committing..."
git add .
if git diff --cached --quiet; then
    echo "No staged changes to commit. Skipping commit and changelog update."
else
    git commit -m "$COMMIT_MESSAGE"
    echo "Git commit successful."

    # 4) Append a simple changelog entry.
    # This is intentionally minimal and can be replaced with PR- or release-based generation.
    echo "Updating CHANGELOG.md..."
    echo -e "\n## $(date +%Y-%m-%d)\n" >> CHANGELOG.md
    echo -e "$COMMIT_MESSAGE\n" >> CHANGELOG.md
    echo "CHANGELOG.md updated."
fi

# 5) Trigger a full project snapshot through the system_utility MCP server.
echo "Creating project snapshot via SystemUtilityServer..."
python3 workspace-automation/src/run_orchestrator_tool.py \
    create_project_snapshot "{}" system_utility
echo "Project snapshot creation initiated."
