"""PR generation module — creates branches, commits, and PRs for auto-fixes."""

import subprocess
from datetime import datetime
from pathlib import Path
from typing import Optional

from review_cycle.models import ScanFinding

HOME = Path.home()


def _branch_name(finding: ScanFinding) -> str:
    safe_repo = finding.repo.lower().replace("/", "-").replace(" ", "-")
    safe_summary = "".join(c if c.isalnum() or c in "-_" else "-" for c in finding.summary.lower())
    safe_summary = safe_summary[:40].strip("-")
    date = datetime.now().strftime("%Y%m%d")
    return f"auto/fix/{date}-{safe_repo}-{safe_summary}"


def _commit_message(finding: ScanFinding) -> str:
    prefix = "feat" if finding.category in ("task_stale",) else "fix"
    return f"{prefix}: auto-fix [{finding.category}] {finding.summary}"


def generate_pr(
    finding: ScanFinding,
    repo_path: Optional[str] = None,
    dry_run: bool = False,
) -> dict:
    repo = repo_path or str(HOME / "Public" / finding.repo)
    branch = _branch_name(finding)
    msg = _commit_message(finding)
    result = {"branch": branch, "message": msg, "success": False, "pr_url": "", "error": ""}

    if dry_run:
        result["success"] = True
        return result

    try:
        subprocess.run(
            ["git", "checkout", "-b", branch],
            cwd=repo, capture_output=True, text=True, check=True,
        )
        subprocess.run(
            ["git", "add", "-A"],
            cwd=repo, capture_output=True, text=True, check=True,
        )
        subprocess.run(
            ["git", "commit", "-m", msg],
            cwd=repo, capture_output=True, text=True, check=True,
        )
        subprocess.run(
            ["git", "push", "origin", branch],
            cwd=repo, capture_output=True, text=True, check=True,
        )
        pr = subprocess.run(
            ["gh", "pr", "create",
             "--title", msg,
             "--body", f"## Auto-fix: {finding.summary}\n\n{finding.detail}\n\n_Generated by review cycle._",
             "--fill"],
            cwd=repo, capture_output=True, text=True, check=True,
        )
        result["pr_url"] = pr.stdout.strip()
        result["success"] = True
    except subprocess.CalledProcessError as e:
        result["error"] = e.stderr[:300]
    except FileNotFoundError:
        result["error"] = "git or gh CLI not found"

    return result
