#!/usr/bin/env bash
# Generate CHANGELOG.md from merged PRs using gh CLI.
# Usage: ./generate_changelog.sh [--since <tag|commit>]

set -euo pipefail

SINCE="${2:-}"
OUTPUT="CHANGELOG.md"

echo "# Changelog" > "$OUTPUT"
echo "" >> "$OUTPUT"
echo "All notable changes to this project will be documented in this file." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "## $(date +%Y-%m-%d)" >> "$OUTPUT"
echo "" >> "$OUTPUT"

if command -v gh &>/dev/null; then
  PRS=$(gh pr list --state merged --limit 20 --json number,title,mergedAt,url --jq '.[] | "\(.mergedAt[:10]) | [#\(.number)](\(.url)) | \(.title)"')
  if [ -n "$PRS" ]; then
    echo "$PRS" | while IFS="|" read -r date pr title; do
      echo "- $title ($pr)" >> "$OUTPUT"
    done
  else
    echo "- (no merged PRs)" >> "$OUTPUT"
  fi
else
  echo "- (gh CLI not available; run with conventional commits)" >> "$OUTPUT"
fi

echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Generated by generate_changelog.sh" >> "$OUTPUT"

echo "Changelog written to $OUTPUT"
