#!/usr/bin/env python3
"""
Continuous Monitoring System - Health tracking with alerts and optimization opportunities

This module provides real-time workspace health monitoring with intelligent alerting,
trend analysis, and optimization opportunity detection. It serves as the central
nervous system for workspace optimization, continuously tracking category health,
file growth patterns, and system performance metrics.

Key Features:
- Real-time health snapshots with comprehensive metrics
- Intelligent alert generation based on configurable thresholds
- Growth trend analysis and predictive insights
- Integration with automation and self-improvement systems
- Performance monitoring and optimization recommendations

Context Resolution:
- Integrates with CategoryAutomation for optimization opportunities
- Feeds data to SelfImprovementSystem for evolution tracking
- Provides alerts to SemanticSearch for context enhancement
- Supports continuous feedback loops for system intelligence
"""

import json
import time
import logging
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, List
from dataclasses import dataclass, asdict
from category_automation import CategoryAutomation
from semantic_search import SemanticSearch

# Configure logging for better error tracking and debugging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

@dataclass
class Alert:
    """
    Alert data structure for system notifications
    
    Represents actionable alerts generated by the monitoring system.
    Each alert contains context about the issue, severity level, and
    whether immediate action is required.
    """
    timestamp: str
    level: str  # info, warning, critical
    category: str
    message: str
    action_required: bool

@dataclass
class HealthMetric:
    """
    Comprehensive health metrics for workspace categories
    
    Tracks multiple dimensions of category health including size,
    growth patterns, organization quality, and diversity metrics.
    Used for trend analysis and predictive optimization.
    """
    category: str
    file_count: int
    growth_rate: float
    balance_score: float
    diversity_index: float
    health_status: str

class ContinuousMonitor:
    """
    Continuous Monitoring System for Workspace Health
    
    This class provides comprehensive monitoring capabilities for workspace
    optimization, including real-time health tracking, alert generation,
    trend analysis, and optimization opportunity detection.
    
    The monitor operates as a central intelligence hub, collecting data
    from various workspace components and providing actionable insights
    for automated optimization systems.
    
    Integration Points:
    - CategoryAutomation: Provides optimization opportunities
    - SemanticSearch: Enhanced context for category analysis  
    - SelfImprovementSystem: Evolution tracking and feedback
    - Dashboard systems: Real-time status and metrics
    
    Configuration:
    All thresholds and parameters are configurable to adapt to
    different workspace sizes and optimization strategies.
    """
    
    def __init__(self):
        """
        Initialize monitoring system with configurable parameters
        
        Sets up workspace paths, loads configuration, initializes
        component integrations, and prepares monitoring infrastructure.
        """
        self.workspace_path = Path("/media/sunil-kr/workspace/user-projects/shared-tools/nested-shares")
        self.monitor_data_file = self.workspace_path / "monitor_data.json"
        
        # Initialize integrated components for comprehensive analysis
        try:
            self.automation = CategoryAutomation()
            self.semantic_search = SemanticSearch()
            logger.info("Successfully initialized monitoring components")
        except Exception as e:
            logger.error(f"Failed to initialize components: {e}")
            # Continue with limited functionality
            self.automation = None
            self.semantic_search = None
        
        # Configurable thresholds for adaptive monitoring
        # These values can be adjusted based on workspace characteristics
        self.thresholds = {
            'critical_size': 200,        # Files threshold for critical alert
            'warning_size': 100,         # Files threshold for warning alert
            'min_size': 3,               # Minimum viable category size
            'max_diversity': 5,          # Maximum file type diversity
            'growth_rate_warning': 0.5   # Growth rate threshold for alerts
        }
        
        # Load historical monitoring data for trend analysis
        self.historical_data = self._load_historical_data()
        
        logger.info(f"Continuous monitor initialized for {self.workspace_path}")
    
    def _load_historical_data(self) -> Dict:
        """
        Load historical monitoring data for trend analysis
        
        Loads previous snapshots, alerts, and health history to enable
        trend analysis, growth rate calculations, and predictive insights.
        
        Returns:
            Dict containing historical snapshots, alerts, and health data
        """
        try:
            if self.monitor_data_file.exists():
                with open(self.monitor_data_file, 'r') as f:
                    data = json.load(f)
                    logger.info(f"Loaded {len(data.get('snapshots', []))} historical snapshots")
                    return data
        except Exception as e:
            logger.error(f"Failed to load historical data: {e}")
        
        # Return empty structure if loading fails
        return {
            'snapshots': [],
            'alerts': [],
            'health_history': []
        }
    
    def _save_data(self):
        """
        Persist monitoring data for historical analysis
        
        Saves current monitoring state including snapshots, alerts,
        and health metrics for future trend analysis and reporting.
        """
        try:
            with open(self.monitor_data_file, 'w') as f:
                json.dump(self.historical_data, f, indent=2)
                logger.debug("Successfully saved monitoring data")
        except Exception as e:
            logger.error(f"Failed to save monitoring data: {e}")
    
    def take_health_snapshot(self) -> Dict:
        """
        Capture comprehensive workspace health snapshot
        
        Performs deep analysis of workspace health including:
        - Category-level health metrics and trends
        - Alert generation based on configurable thresholds
        - Overall workspace health assessment
        - Integration with optimization systems for actionable insights
        
        This is the core monitoring function that provides real-time
        workspace intelligence for automated optimization systems.
        
        Returns:
            Dict containing comprehensive health snapshot with metrics,
            alerts, and optimization recommendations
        """
        logger.info("Taking comprehensive health snapshot")
        
        snapshot = {
            'timestamp': datetime.now().isoformat(),
            'categories': {},
            'overall_health': 'healthy',
            'total_files': 0,
            'alerts_generated': []
        }
        
        alerts = []
        total_files = 0
        
        # Analyze each category for comprehensive health assessment
        for cat_dir in self.workspace_path.iterdir():
            if not cat_dir.is_dir() or cat_dir.name.startswith('.'):
                continue
            
            try:
                category = cat_dir.name
                health_metric = self._assess_category_health(cat_dir, category)
                snapshot['categories'][category] = asdict(health_metric)
                total_files += health_metric.file_count
                
                # Generate intelligent alerts based on health assessment
                category_alerts = self._generate_category_alerts(health_metric)
                alerts.extend(category_alerts)
                
                logger.debug(f"Analyzed category {category}: {health_metric.file_count} files, {health_metric.health_status}")
                
            except Exception as e:
                logger.error(f"Failed to analyze category {cat_dir.name}: {e}")
                continue
        
        snapshot['total_files'] = total_files
        snapshot['alerts_generated'] = [asdict(alert) for alert in alerts]
        
        # Determine overall workspace health based on category analysis
        critical_alerts = [a for a in alerts if a.level == 'critical']
        warning_alerts = [a for a in alerts if a.level == 'warning']
        
        if critical_alerts:
            snapshot['overall_health'] = 'critical'
        elif warning_alerts:
            snapshot['overall_health'] = 'warning'
        
        # Store snapshot for historical trend analysis
        self.historical_data['snapshots'].append(snapshot)
        self.historical_data['alerts'].extend([asdict(a) for a in alerts])
        
        # Maintain reasonable history size for performance
        if len(self.historical_data['snapshots']) > 50:
            self.historical_data['snapshots'] = self.historical_data['snapshots'][-50:]
        
        # Persist data for future analysis
        self._save_data()
        
        logger.info(f"Health snapshot complete: {total_files} files, {len(alerts)} alerts, {snapshot['overall_health']} status")
        
        return snapshot
    
    def _assess_category_health(self, cat_path: Path, category: str) -> HealthMetric:
        """Assess health of a single category"""
        files = [f for f in cat_path.rglob("*") if f.is_file()]
        file_count = len(files)
        
        # Calculate diversity index
        file_types = {}
        for file_path in files:
            ext = file_path.suffix.lower()
            file_types[ext] = file_types.get(ext, 0) + 1
        
        diversity_index = len(file_types)
        
        # Calculate growth rate
        growth_rate = self._calculate_growth_rate(category, file_count)
        
        # Calculate balance score (how well organized)
        balance_score = self._calculate_balance_score(cat_path, file_count, diversity_index)
        
        # Determine health status
        health_status = self._determine_health_status(file_count, diversity_index, growth_rate, balance_score)
        
        return HealthMetric(
            category=category,
            file_count=file_count,
            growth_rate=growth_rate,
            balance_score=balance_score,
            diversity_index=diversity_index,
            health_status=health_status
        )
    
    def _calculate_growth_rate(self, category: str, current_count: int) -> float:
        """Calculate growth rate compared to previous snapshot"""
        if len(self.historical_data['snapshots']) < 2:
            return 0.0
        
        prev_snapshot = self.historical_data['snapshots'][-1]
        if category in prev_snapshot['categories']:
            prev_count = prev_snapshot['categories'][category]['file_count']
            if prev_count > 0:
                return (current_count - prev_count) / prev_count
        
        return 0.0
    
    def _calculate_balance_score(self, cat_path: Path, file_count: int, diversity_index: int) -> float:
        """Calculate how well-balanced/organized a category is"""
        if file_count == 0:
            return 1.0
        
        # Check subcategory organization
        subdirs = [d for d in cat_path.iterdir() if d.is_dir()]
        has_subcategories = len(subdirs) > 0
        
        # Balance factors
        size_balance = 1.0 - min(file_count / 200, 1.0)  # Penalty for large size
        diversity_balance = 1.0 - min(diversity_index / 10, 1.0)  # Penalty for high diversity
        organization_bonus = 0.2 if has_subcategories and file_count > 20 else 0
        
        return max(0.0, min(1.0, size_balance + diversity_balance + organization_bonus))
    
    def _determine_health_status(self, file_count: int, diversity: int, growth_rate: float, balance: float) -> str:
        """Determine overall health status"""
        if file_count > self.thresholds['critical_size'] or diversity > self.thresholds['max_diversity']:
            return 'critical'
        elif file_count > self.thresholds['warning_size'] or growth_rate > self.thresholds['growth_rate_warning']:
            return 'warning'
        elif file_count < self.thresholds['min_size']:
            return 'attention'
        else:
            return 'healthy'
    
    def _generate_category_alerts(self, health_metric: HealthMetric) -> List[Alert]:
        """Generate alerts for category health issues"""
        alerts = []
        timestamp = datetime.now().isoformat()
        category = health_metric.category
        
        # Critical size alert
        if health_metric.file_count > self.thresholds['critical_size']:
            alerts.append(Alert(
                timestamp=timestamp,
                level='critical',
                category=category,
                message=f"Category oversized: {health_metric.file_count} files (threshold: {self.thresholds['critical_size']})",
                action_required=True
            ))
        
        # Warning size alert
        elif health_metric.file_count > self.thresholds['warning_size']:
            alerts.append(Alert(
                timestamp=timestamp,
                level='warning',
                category=category,
                message=f"Category approaching size limit: {health_metric.file_count} files",
                action_required=False
            ))
        
        # High diversity alert
        if health_metric.diversity_index > self.thresholds['max_diversity']:
            alerts.append(Alert(
                timestamp=timestamp,
                level='warning',
                category=category,
                message=f"High diversity: {health_metric.diversity_index} file types (consider subcategorization)",
                action_required=False
            ))
        
        # Rapid growth alert
        if health_metric.growth_rate > self.thresholds['growth_rate_warning']:
            alerts.append(Alert(
                timestamp=timestamp,
                level='warning',
                category=category,
                message=f"Rapid growth: {health_metric.growth_rate:.1%} increase",
                action_required=False
            ))
        
        # Low balance alert
        if health_metric.balance_score < 0.3:
            alerts.append(Alert(
                timestamp=timestamp,
                level='info',
                category=category,
                message=f"Poor organization: balance score {health_metric.balance_score:.2f}",
                action_required=False
            ))
        
        return alerts
    
    def get_active_alerts(self, hours: int = 24) -> List[Alert]:
        """Get alerts from the last N hours"""
        cutoff = datetime.now() - timedelta(hours=hours)
        active_alerts = []
        
        for alert_data in self.historical_data['alerts']:
            alert_time = datetime.fromisoformat(alert_data['timestamp'])
            if alert_time > cutoff:
                active_alerts.append(Alert(**alert_data))
        
        return active_alerts
    
    def get_health_trends(self) -> Dict:
        """Analyze health trends over time"""
        if len(self.historical_data['snapshots']) < 2:
            return {'error': 'Insufficient data for trend analysis'}
        
        trends = {
            'overall_trend': 'stable',
            'category_trends': {},
            'growth_categories': [],
            'declining_categories': []
        }
        
        recent_snapshots = self.historical_data['snapshots'][-10:]  # Last 10 snapshots
        
        for category in recent_snapshots[-1]['categories'].keys():
            file_counts = []
            for snapshot in recent_snapshots:
                if category in snapshot['categories']:
                    file_counts.append(snapshot['categories'][category]['file_count'])
            
            if len(file_counts) >= 2:
                trend = 'growing' if file_counts[-1] > file_counts[0] else 'stable'
                if file_counts[-1] < file_counts[0]:
                    trend = 'declining'
                
                trends['category_trends'][category] = {
                    'trend': trend,
                    'change': file_counts[-1] - file_counts[0],
                    'current_size': file_counts[-1]
                }
                
                if trend == 'growing' and file_counts[-1] > 50:
                    trends['growth_categories'].append(category)
                elif trend == 'declining':
                    trends['declining_categories'].append(category)
        
        return trends
    
    def get_optimization_opportunities(self) -> Dict:
        """Get current optimization opportunities"""
        # Get automation opportunities
        auto_opportunities = self.automation.analyze_automation_opportunities()
        
        # Get semantic analysis
        semantic_analysis = self.semantic_search.cross_category_analysis()
        
        # Combine insights
        opportunities = {
            'immediate_actions': [],
            'optimization_suggestions': [],
            'monitoring_insights': []
        }
        
        # Add automation opportunities
        for split in auto_opportunities['auto_splits']:
            if split['priority'] == 'high':
                opportunities['immediate_actions'].append({
                    'type': 'split',
                    'category': split['category'],
                    'reason': f"{split['files']} files exceed threshold"
                })
        
        # Add semantic suggestions
        for merge in semantic_analysis['merge_suggestions']:
            opportunities['optimization_suggestions'].append({
                'type': 'merge',
                'categories': merge['categories'],
                'reason': merge['reason']
            })
        
        # Add monitoring insights
        trends = self.get_health_trends()
        if 'growth_categories' in trends:
            for category in trends['growth_categories']:
                opportunities['monitoring_insights'].append({
                    'type': 'growth_alert',
                    'category': category,
                    'reason': 'Rapid growth detected'
                })
        
        return opportunities
    
    def run_continuous_monitoring(self, interval_minutes: int = 60):
        """Run continuous monitoring loop"""
        print(f"🔄 Starting continuous monitoring (interval: {interval_minutes} minutes)")
        
        while True:
            try:
                print(f"\n📊 Taking health snapshot at {datetime.now().strftime('%H:%M:%S')}")
                snapshot = self.take_health_snapshot()
                
                # Report critical alerts
                critical_alerts = [a for a in snapshot['alerts_generated'] if a['level'] == 'critical']
                if critical_alerts:
                    print(f"🚨 {len(critical_alerts)} CRITICAL ALERTS:")
                    for alert in critical_alerts:
                        print(f"   • {alert['category']}: {alert['message']}")
                
                print(f"✅ Health: {snapshot['overall_health']} | Files: {snapshot['total_files']} | Alerts: {len(snapshot['alerts_generated'])}")
                
                # Sleep until next check
                time.sleep(interval_minutes * 60)
                
            except KeyboardInterrupt:
                print("\n🛑 Monitoring stopped by user")
                break
            except Exception as e:
                print(f"❌ Monitoring error: {e}")
                time.sleep(60)  # Wait 1 minute before retry

def main():
    import sys
    
    monitor = ContinuousMonitor()
    
    if len(sys.argv) < 2:
        print("Usage: python3 continuous_monitor.py <command>")
        print("Commands:")
        print("  snapshot    - Take health snapshot")
        print("  alerts      - Show active alerts")
        print("  trends      - Show health trends")
        print("  optimize    - Show optimization opportunities")
        print("  run [mins]  - Run continuous monitoring")
        return
    
    command = sys.argv[1]
    
    if command == 'snapshot':
        snapshot = monitor.take_health_snapshot()
        
        print("📊 Health Snapshot")
        print("=" * 20)
        print(f"Overall Health: {snapshot['overall_health']}")
        print(f"Total Files: {snapshot['total_files']}")
        print(f"Alerts Generated: {len(snapshot['alerts_generated'])}")
        
        print("\n📁 Category Health:")
        for category, health in snapshot['categories'].items():
            status_emoji = {'healthy': '✅', 'warning': '⚠️', 'critical': '🚨', 'attention': '👀'}
            emoji = status_emoji.get(health['health_status'], '❓')
            print(f"  {emoji} {category}: {health['file_count']} files ({health['health_status']})")
        
        if snapshot['alerts_generated']:
            print(f"\n🚨 New Alerts ({len(snapshot['alerts_generated'])}):")
            for alert in snapshot['alerts_generated']:
                level_emoji = {'critical': '🚨', 'warning': '⚠️', 'info': 'ℹ️'}
                emoji = level_emoji.get(alert['level'], '❓')
                print(f"  {emoji} {alert['category']}: {alert['message']}")
    
    elif command == 'alerts':
        alerts = monitor.get_active_alerts(24)
        
        print("🚨 Active Alerts (24h)")
        print("=" * 25)
        
        if not alerts:
            print("No active alerts")
            return
        
        by_level = {'critical': [], 'warning': [], 'info': []}
        for alert in alerts:
            by_level[alert.level].append(alert)
        
        for level in ['critical', 'warning', 'info']:
            if by_level[level]:
                level_emoji = {'critical': '🚨', 'warning': '⚠️', 'info': 'ℹ️'}
                print(f"\n{level_emoji[level]} {level.upper()} ({len(by_level[level])}):")
                for alert in by_level[level]:
                    time_str = datetime.fromisoformat(alert.timestamp).strftime('%H:%M')
                    print(f"  [{time_str}] {alert.category}: {alert.message}")
    
    elif command == 'trends':
        trends = monitor.get_health_trends()
        
        print("📈 Health Trends")
        print("=" * 15)
        
        if 'error' in trends:
            print(trends['error'])
            return
        
        if trends['growth_categories']:
            print(f"\n📈 Growing Categories ({len(trends['growth_categories'])}):")
            for category in trends['growth_categories']:
                trend_info = trends['category_trends'][category]
                print(f"  • {category}: +{trend_info['change']} files (now {trend_info['current_size']})")
        
        if trends['declining_categories']:
            print(f"\n📉 Declining Categories ({len(trends['declining_categories'])}):")
            for category in trends['declining_categories']:
                trend_info = trends['category_trends'][category]
                print(f"  • {category}: {trend_info['change']} files (now {trend_info['current_size']})")
        
        stable_categories = [cat for cat, info in trends['category_trends'].items() 
                           if info['trend'] == 'stable']
        if stable_categories:
            print(f"\n📊 Stable Categories ({len(stable_categories)}):")
            for category in stable_categories[:5]:  # Show first 5
                trend_info = trends['category_trends'][category]
                print(f"  • {category}: {trend_info['current_size']} files")
    
    elif command == 'optimize':
        opportunities = monitor.get_optimization_opportunities()
        
        print("🎯 Optimization Opportunities")
        print("=" * 30)
        
        if opportunities['immediate_actions']:
            print(f"\n🚨 Immediate Actions ({len(opportunities['immediate_actions'])}):")
            for action in opportunities['immediate_actions']:
                print(f"  • {action['type'].title()} {action['category']}: {action['reason']}")
        
        if opportunities['optimization_suggestions']:
            print(f"\n💡 Optimization Suggestions ({len(opportunities['optimization_suggestions'])}):")
            for suggestion in opportunities['optimization_suggestions']:
                if suggestion['type'] == 'merge':
                    print(f"  • Merge {' + '.join(suggestion['categories'])}: {suggestion['reason']}")
        
        if opportunities['monitoring_insights']:
            print(f"\n📊 Monitoring Insights ({len(opportunities['monitoring_insights'])}):")
            for insight in opportunities['monitoring_insights']:
                print(f"  • {insight['category']}: {insight['reason']}")
        
        if not any([opportunities['immediate_actions'], opportunities['optimization_suggestions'], opportunities['monitoring_insights']]):
            print("\n✨ No optimization opportunities found - workspace is well-maintained!")
    
    elif command == 'run':
        interval = int(sys.argv[2]) if len(sys.argv) > 2 else 60
        monitor.run_continuous_monitoring(interval)

if __name__ == "__main__":
    main()
